feat: sync kustomize task

diff --git a/charts/tekton-pipelines/templates/common/tasks/kustomize.yaml b/charts/tekton-pipelines/templates/common/tasks/kustomize.yaml
--- a/charts/tekton-pipelines/templates/common/tasks/kustomize.yaml
+++ b/charts/tekton-pipelines/templates/common/tasks/kustomize.yaml
@@ -63,15 +63,32 @@ spec:
       workingDir: $(resources.inputs.kubernetes-repo.path)      
       script: |    
         set +x
+        git checkout $(params.kubernetes_branch)
+
         # apply changes only if it exists, otherwise do nothing
         if [ $(git status --porcelain | wc -l) -eq 0 ]; then
           echo "There are no changes, nothing to commit"
           exit
         fi
 
-        # the params.branch comes from github push event and looks like this: "refs/heads/staging"
-        # so we had to get only the end of the string        
-        git commit -am "feat: $(params.environment) argocd deployment $(params.kustomize_overlay_path), new image: $(params.image)"
-        # mkdir /root/.ssh && cp -r $HOME/.ssh/* /root/.ssh
-        # git push
-        git push origin HEAD:$(params.kubernetes_branch)
+        # define retry delays appropriate for dash
+        set -- "0" "1" "3" "5"
+        for DELAY
+        do
+          if [ "$DELAY" != "0" ]; then
+            echo "retry in ${DELAY}s"
+          fi
+          sleep $DELAY
+
+          # check whether there are changes between local and remote
+          git fetch origin $(params.kubernetes_branch)
+          LOCAL_COMMIT=`git rev-parse @`
+          REMOTE_COMMIT=`git rev-parse origin/$(params.kubernetes_branch)`
+          if [ $LOCAL_COMMIT != $REMOTE_COMMIT ]; then
+            echo "Need to pull new changes"
+            git pull origin HEAD:$(params.kubernetes_branch)
+          fi
+
+          git commit -am "feat: $(params.environment) argocd deployment $(params.kustomize_overlay_path), new image: $(params.image)"
+          git push origin HEAD:$(params.kubernetes_branch) && break || true
+        done
